### ISSUE TITLE
fixes for cupy 9.x

### ISSUE THREAD

**Issue by kashif** [tk-rusch/unicornn#1]
For `cupy` version 9.x you can just:

```py
import cupy as cp

...

mod = cp.RawModule(code=UnICORNN_CODE, options=('--std=c++11',),
        name_expressions=('unicornn_fwd', 'unicornn_bwd'))
...
```

which seems to work and you don't need to go through `pynvrtc` etc.

**Comment by tk-rusch** [comment]
Many thanks for the valuable remark! I just tried your suggestion and it worked -- good way to reduce the amount of requirements.
I will make a comment in the requirements section of the readme.
If there is nothing else you want to mention regarding that, please feel free to close this issue.

**Comment by kashif** [comment]
on a side note, i want to understand the model more... from the dynamical system side of things but that's a separate issue. Closing!

**Comment by tk-rusch** [comment]
If you have any theoretical questions regarding UnICORNN, you can contact me anytime (e.g. by e-mail).
